### ISSUE TITLE
Agendas for the meeting - 2014/11/14

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#11]
# Agendas
## General Issues
- On the vision - see this text. 
  https://github.com/leehosung/writing_sandbox/wiki/Let's-Make-SANDBOX!
- License - contents, source will be open. Hosung will choose an appropriate license. #22 
- On reusing feedback as quiz content - when giving feedback, teachers will follow a formatting rule.  #16, #19
- How we will communicate about the project #17
- A new domain? A new brand name - Nasol will gather ideas in the FB group.
## On preparation for the 1st offline-meeting
- Nasol will make two quiz sets including 30 sentences. (Google Spreadsheet will be temporarily used for Admin #15)
- Lee Hosung will prepare for the briefing for the potential participants of the project.
-   \* Of what CI consists of?
-   \* Why python 3 and Django?
-   \* What paticipants need to know in order to contribute. 
- Lee Hosung will choose a code style and modify the current codes. #21
- The date for the first offline meeting is planned to be 2014/12/9 (Tue)
## On running the service
- The service will be temporarily run on the AWS that Hosung has. #20

**Comment by leehosung** [comment]
What do you think about this issue?

**Comment by nassol** [comment]
@leehosung Should I close this issue?
