### ISSUE TITLE
Deploying on Azure

### ISSUE THREAD

**Issue by leehosung** [leehosung/writing_sandbox#12]
I want to use Microsoft Azure on the production environment. 

@nassol. You told me that we can be supported Azure by Meltingpot program. How can I use that?

**Comment by nassol** [comment]
@leehosung I'll add you to the secret group of Melting pot. You can ask Mira do there :)

**Comment by leehosung** [comment]
Thank you! You mentioned person who has no relation with this project :)

**Comment by nassol** [comment]
@leehosung oh! oh! That was a mistake!

**Comment by leehosung** [comment]
We can use Azure for just one month. T.T. I will use AWS instead of it.
