### ISSUE TITLE
Temporary Admin Site - Google Spreadsheet

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#15]
For the time being, we will use this file as an Admin Site where teachers can type in sentences.for quiz sets.

https://docs.google.com/spreadsheets/d/1IZrjQL--YaxLdPKBbGCtzelKlB2i4x0cyoV9b1fVkMM/edit#gid=0

**Comment by leehosung** [comment]
This issue is duplicated with #25 isn't it?

**Comment by nassol** [comment]
@leehosung That's right, I'll close this issue! or... should I delete it??

**Comment by leehosung** [comment]
Yes you can but I think it is not a good idea to delete the history of project.

**Comment by nassol** [comment]
Is that right? Then, I'll just leave it closed.
