### ISSUE TITLE
On communicating about the project

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#17]
### Github Issues board

The discussions will occure mainly in the [Github issue board](https://github.com/leehosung/writing_sandbox/issues).
### Facebook Group

When an issue needs various opinions from many people, the issue will be shared to the Facebook group. https://www.facebook.com/groups/engfordev/
### Real-time communication

For real-time communication we will use a Gitter chat room. 
[![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/leehosung/writing_sandbox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
### On-/offline meeting - webinar/ TOZ

Admins will organize necessary meetings either online or offline.

**Comment by leehosung** [comment]
I think we would better move this description to readme.md

**Comment by nassol** [comment]
@leehosung Yeap,you're right. I'll put these in the readme.md and close this issue! Thanks!
