### ISSUE TITLE
Deployment setting

### ISSUE THREAD

**Issue by leehosung** [leehosung/writing_sandbox#2]
- preparing server to deploy this service. 
- setting up a domain name (sandbox.novice.io) and connect it to the server.

**Comment by leehosung** [comment]
I deployed this service to Heroku(www.heroku.com) and I set up the CI(continuous integration) using Travis(https://travis-ci.org). When I push commits to master branch, it will be applied to the production server in Heroku.

**Comment by leehosung** [comment]
@nassol. Can you give me a feedback? ^^

**Comment by nassol** [comment]
Just minor points in grammar. But the intention is well conveyed I think.

When I push commits to "the" master branch, "they(the commits)" will be applied to the production server in Heroku.

By the way, I just thought that this kind of information is something we need to include in a Wiki page for those who are willing to contribute as a programmer.

**Comment by leehosung** [comment]
Yes. you are right. Before "Grand open" I have to finish writing "How to contribute" in the readme file.

**Comment by nassol** [comment]
@leehosung Hey, I've read something about CONTRIBUTE.md file. I don't really understand the meaning of that Github now supports contribute.md file. What do you think it means? 

And do you think we need to create a contribute.md file and fill it up? 
I wrote something about contributing here.. It's not complete but.. 
https://github.com/leehosung/writing_sandbox/wiki/How-to-contribute

**Comment by nassol** [comment]
@leehosung  By the way,  "Grand opening" seems to be idiomatic :)

https://www.google.co.kr/search?q=grand+open&newwindow=1&es_sm=93&source=lnms&tbm=isch&sa=X&ei=jpdhVK_AE-bOmwWJ7oLwBA&ved=0CAgQ_AUoAQ&biw=1304&bih=683#newwindow=1&tbm=isch&q=grand+opening

**Comment by leehosung** [comment]
@nassol Oh! yes. but I am familiar with "Grand open" instead of "grand opening" ^^

**Comment by leehosung** [comment]
And I also have some idea about the contributing. Let's talk about it on this Friday. And why don't you open a new issue?

**Comment by nassol** [comment]
@leehosung Yes, sir!
