### ISSUE TITLE
Coding convention for Python 

### ISSUE THREAD

**Issue by leehosung** [leehosung/writing_sandbox#21]
We use the PEP-8 coding conventions for our python code so need a refactoring some code.

**Comment by leehosung** [comment]
I refactor code to meet PEP8. And I add a small script to check the style of Python code on a CI server.

**Comment by nassol** [comment]
@leehosung You will, or you did?

**Comment by leehosung** [comment]
I did it.

**Comment by nassol** [comment]
Thanks!!
