### ISSUE TITLE
About naming - keeping Writing Sandbox

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#23]
Why don't we use "writing sandbox" for our prototype? I considered discussing this in the FB group but I thought for coming up with a new, nice and appropriate name we need to have a deep understanding about the program. And for deep understanding we will need to participate in the b project.

So I thought we could keep this name or change it when some meaningful number of participants get a good sense of the project.

**Comment by leehosung** [comment]
Okay. I agree with you so our DNS for site will be "http://writing-sandbox.novice.io"

**Comment by nassol** [comment]
@leehosung Yeap! Cool!

**Comment by leehosung** [comment]
Cool!!
