### ISSUE TITLE
Register sentences for quizzes to the Google Spread Sheet for Admin

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#25]
This is necessary for opening up the prototype! 

About 30 sentences of 3 categories will be good.

https://docs.google.com/spreadsheets/d/1IZrjQL--YaxLdPKBbGCtzelKlB2i4x0cyoV9b1fVkMM/edit#gid=0

**Comment by nassol** [comment]
I've done it!

**Comment by leehosung** [comment]
Good Job!
