### ISSUE TITLE
Add some descriptions to the category title 

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#27]
## What needs to be developed
- Add description of categories
- Description is about motivating users telling about why they are practicing this category. 
- QnA - 스택오버플로우에서 활동하려면, 영어로 질문하고 답변할 수 있어야겠죠?
- Issue - 유저 사용 흐름, 버그를 신고하는 내용 등을 영어로 써봅니다. 
## Why it is needed
- The space can be useful for something to motivate our users. 
## how a user will use it
- A user chooses a category to practice. 
- He sees a description after the category name

![sandbox2](https://cloud.githubusercontent.com/assets/1484976/5138030/25082bac-718a-11e4-8cb1-1e01db77013c.png)

**Comment by leehosung** [comment]
That is a good idea. And the included picture makes me understand easily. Thank you!

**Comment by nassol** [comment]
:)

**Comment by nassol** [comment]
Hum.. I don't see any descriptions after the category title. Can you please check it out?

![01](https://cloud.githubusercontent.com/assets/1484976/5375720/c12d46d6-80b0-11e4-81e8-9e5c88b4c742.png)
