### ISSUE TITLE
Receive feedback from users

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#31]
I'd like to use this google form to receive feedback from users.

Please add this link on a menu as in the picture below: 
- link : https://docs.google.com/forms/d/1Ea_K3YN0POcgYZuANjL_qIUKvuqfYQ1lJIPmOYnUkr4/viewform

![image](https://cloud.githubusercontent.com/assets/1484976/5356477/4c102056-7fe0-11e4-872b-d0b1a81f3b68.png)

**Comment by leehosung** [comment]
How about "Send feedback" as a button name?

**Comment by nassol** [comment]
Thanks!!
