### ISSUE TITLE
Question - Is it possible to transfer Wiki content to another's repository? 

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#6]
Actually I wrote something on a Wiki page on my repository.
But it doesn't show up in the Hosung's Wiki.
Is it possible to transfer the content of my wiki to Hosungs?

**Comment by leehosung** [comment]
No. It is not available. Please see the following link.
https://github.com/gollum/gollum/issues/265
To write wiki with others, the repository should be moved under a group instead of a person. 
After prototyping, I will move this project under a group.

**Comment by nassol** [comment]
A-ha! Got it. Thanks! 

What do you think about moving this project later on to this organization.. https://github.com/EngForDev? Or would you prefer a separate clean one?

**Comment by leehosung** [comment]
Oh. There is already group. I will move this right now.

**Comment by leehosung** [comment]
can you invite me?

**Comment by leehosung** [comment]
I add you as a collaborator and grant a full access control on this project. 
now you can edit wiki. try it!

**Comment by nassol** [comment]
@leehosung  Thanks! and I've sent you an invitation to the group!
