### ISSUE TITLE
minor feature - to make it not disappear the English sentence that a user typed in.

### ISSUE THREAD

**Issue by nassol** [leehosung/writing_sandbox#8]
http://writing-sandbox.herokuapp.com/

When a learner types enter after typing in his sentence in English,
now what he typed in disappears.

Let's change this so that what he typed does not disappear.

**Comment by leehosung** [comment]
Thanks for your report. I will fix it as soon as possible.

**Comment by nassol** [comment]
@leehosung Thanks! :)

**Comment by leehosung** [comment]
Now you can see your answer after hit the enter. After checking the change, please close this issue.

**Comment by nassol** [comment]
@leehosung It works good!
