### ISSUE TITLE
GUI testing on travis

### ISSUE THREAD

**Issue by leehosung** [leehosung/writing_sandbox#9]
Travis doesn't support GUI and browser testing which is using Selenium.
So to test GUI we have to set up Sauce Labs(https://saucelabs.com/account).

http://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by nassol** [comment]
Travis doesn't support GUI and browser testing which is using Selenium.
<= what does 'which' refer to? 

I'd rather put commas.
So, to test GUI, we have to set up Sauce Labs

**Comment by leehosung** [comment]
'which' refers to "GUI and browser testing" 
Thanks for your kind comment!
By the way, I finished this issue!

**Comment by nassol** [comment]
if 'which' refers to the two items, 

which is using -> which are using

Thanks!!
